stages:
- stage: Test
  jobs:
  - job: Test
    strategy:
      matrix: 
        'Python 3.6/Linux':
          image: 'ubuntu-20.04'
          pythonVersion: '3.6'
        'Python 3.7/Linux':
          image: 'ubuntu-20.04'
          pythonVersion: '3.7'
        'Python 3.8/Linux':
          image: 'ubuntu-20.04'
          pythonVersion: '3.8'
        'Windows Server 2019':
          image: 'windows-2019'
          pythonVersion: '3.8'

    pool:
      vmImage: $(image)

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'

    - script: |
        pip install -U poetry
        pip install -U tox
      displayName: 'Install Poetry'

    - bash: |
        PYENV=$(sed -e 's/\.//' <<< "py$(pythonVersion)")
        poetry run tox -e $PYENV
      displayName: 'Running tests via tox'
