stages:
- stage: Test
  pool: StageAPool
  jobs:
  - job: A1 # will run on "StageAPool" pool based on the pool defined on the stage
  - job: A2 # will run on "JobPool" pool
    pool: JobPool


  jobs:
  - job: Test
    strategy:
      matrix: 
        US_IE:
          Location: US
          Browser: IE
        US_Chrome:
          Location: US
          Browser: Chrome
        Europe_Chrome:
          Location: Europe
          Browser: Chrome

        'Python 3.6/Linux':
          image: 'ubuntu-20.04'
          python.version: '3.6'
        'Python 3.7/Linux':
          image: 'ubuntu-20.04'
          python.version: '3.7'
        'Python 3.8/Linux':
          image: 'ubuntu-20.04'
          python.version: '3.8'
        'Windows Server 2019':
          image: 'windows-2019'
          python.version: '3.8'

    pool:
      vmImage: $(image)

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'

    - script: |
        pip install -U poetry
      displayName: 'Install Poetry'

    - script: make init-dev
      displayName: 'Install dependencies'

    - script: poetry run tox -e $[replace(variables['python.version'], '.', '')]
      displayName: 'Running tests via tox'
